# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install pypinyin
        python -m pip install Pillow

    - name: Test with pytest
      run: |
          python -m unittest pyefun.arithmeticOperationBase_test
          python -m unittest pyefun.arrayActionBase_test
          python -m unittest pyefun.cacheUtil_test
          python -m unittest pyefun.clockUtil_test
          python -m unittest pyefun.codeConv_test
          #python -m unittest pyefun.commonlyUtil_test #有问题无法自动测试
          python -m unittest pyefun.configEnvUtil_test
          python -m unittest pyefun.configUtil_test
          #python -m unittest pyefun.dirkBase_test  #有问题无法自动测试
          python -m unittest pyefun.ewin32api_test
          python -m unittest pyefun.imageUtil_test # 缺少依赖 ModuleNotFoundError: No module named 'PIL'
          python -m unittest pyefun.networkUtil_test
          python -m unittest pyefun.processPoolUtil_test
          python -m unittest pyefun.progiterUtil_test
          #python -m unittest pyefun.regexpUtil_test #有问题无法自动测试
          python -m unittest pyefun.stringBase_test
          python -m unittest pyefun.stringUtil_test
          python -m unittest pyefun.systemProcessingBase_test
          #python -m unittest pyefun.threadingUtil_test #有问题无法自动测试
          python -m unittest pyefun.timeBase_test
          python -m unittest pyefun.timeUtil_test
          python -m unittest pyefun.typeConv_test

